# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcaab1af8d8a1b0d53dc89b1d092e36d0f74bcb585e491921d0e2d3f1351f14b93fdc37e87bfb17d79cf4b049f8321ab2d68dfa975f6bb8452f30f5a4aeaf30b

test:
  secret_key_base: 9d95f0103fe3e10b7e3d6ce8a9c3e093e90e1ea0616f9a825224a65b6714bdea2a964a4242dc9b6a8db536aa624fe16c0e0320239d0325474873ed99312a1a6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
